const state={page:"home",admin:false,data:loadAppData(),selectedDates:["2026-08-14","2026-08-15","2026-08-16","2026-08-17"],selectedChoices:new Set()};
function labels(){return state.data.settings.labels}
function navItems(){const l=labels();return [["home","⌂",l.home],["schedule","▣",l.meeting],["choice","▭",l.choice],["shelf","▥",l.shelf],["people","♙",l.participants],["history","◷",l.history],["messages","▤",l.messages],["more","•••",l.more]]}
function applyIdentity(){const i=state.data.settings.identity;document.documentElement.style.setProperty("--green",i.primaryColor);document.documentElement.style.setProperty("--green2",i.secondaryColor);document.documentElement.style.setProperty("--cream",i.creamColor);document.getElementById("themeMeta").content=i.primaryColor;document.getElementById("brandEyebrow").textContent=i.clubEyebrow;document.getElementById("brandName").textContent=i.clubName;document.getElementById("quoteText").textContent=i.quote;document.getElementById("quoteAuthor").textContent="– "+i.quoteAuthor}
function navItems(){return [["home","⌂","Início"],["schedule","▣","Encontro"],["choice","▱","Escolha do Livro"],["shelf","♧","Estante"],["people","♙","Participantes"],["history","◷","Histórico"],["about","ⓘ","Sobre o Clube"]]}
function save(msg=""){persistAppData(state.data);window.dispatchEvent(new CustomEvent("biblioteca:save",{detail:state.data}));applyIdentity();render();if(msg)showToast(msg)}
function renderNav(){const html=navItems().map(([p,ic,l])=>`<button class="${state.page===p?"active":""}" data-page="${p}"><span>${ic}</span>${escapeHtml(l)}</button>`).join("");desktopNav.innerHTML=html;mobileNav.innerHTML=navItems().slice(0,5).map(([p,ic,l])=>`<button class="${state.page===p?"active":""}" data-page="${p}"><span>${ic}</span><small>${escapeHtml(l)}</small></button>`).join("")}
function countFor(date,period){return state.data.availability.responses.filter(r=>r.choices.includes(`${date}|${period}`)).length}
function bestOptions(){let out=[];["2026-08-14","2026-08-15","2026-08-16","2026-08-17"].forEach(d=>state.data.availability.periods.forEach(p=>out.push({date:d,period:p,count:countFor(d,p.id)})));return out.sort((a,b)=>b.count-a.count)}
function home(){
 const b=state.data.currentBook,best=state.selectedDates.slice(0,4).map((d,i)=>({count:Math.max(2,5-i),period:{label:new Date(d+"T12:00:00").toLocaleDateString("pt-BR",{weekday:"long"}).replace("-feira",""),hint:new Date(d+"T12:00:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"long"})}}));
 return `<header class="greeting"><div><h1>Boa noite, Juliana! ✦</h1><p>Que bom ter você aqui.</p></div><div class="header-icons">♧ ▣</div></header>
 <section class="top-grid">
  <article class="panel meeting-card"><span class="eyebrow">✦ ENCONTRO DE AGOSTO ✦</span><div class="meeting-body"><img class="main-cover" src="${b.cover}"><div><h2>${b.title}</h2><h3>${b.author}</h3><p>${b.description}</p><div class="meeting-meta">▣ ${b.meetingDate}<br>◷ ${b.meetingTime} · Horário confirmado</div></div><img class="deco" src="assets/illustrations/books-flowers.svg"></div></article>
  <article class="panel upcoming"><span class="eyebrow">PRÓXIMOS ENCONTROS</span>${state.data.upcomingMeetings.map(m=>`<div class="upcoming-row"><strong>${m.month}</strong><span>${m.date}</span><small>${m.book}</small></div>`).join("")}<button class="outline" data-page="schedule">▣ Ver calendário completo</button></article>
 </section>
 <section class="panel availability-summary"><div class="section-title"><div><span class="eyebrow">ESCOLHA DO HORÁRIO</span><p>Resumo das disponibilidades</p></div><button class="link-btn" data-page="schedule">Ver todos os horários →</button></div><div class="availability-cards">${best.map((x,i)=>`<article class="${i===0?"best":""}"><strong>${x.period.label}</strong><div class="people-icons">${"●".repeat(x.count)}${"○".repeat(Math.max(0,8-x.count))}</div><span>${x.count} de 8<br>pode</span></article>`).join("")}</div><img class="corner-illustration" src="assets/illustrations/cup-books.svg"></section>
 <section class="middle-grid">
  <article class="panel participants-box"><div class="section-title"><div><span class="eyebrow">PARTICIPANTES</span><p>5 de 8 responderam</p></div><button class="link-btn" data-page="people">Ver todos →</button></div><div class="avatar-row">${state.data.participants.map((p,i)=>`<div><img src="${p.photo}"><small>${i===0?"Você":p.name}</small>${i<5?`<b>✓</b>`:""}</div>`).join("")}</div></article>
  <article class="panel recent-books"><div class="section-title"><span class="eyebrow">ÚLTIMOS LIVROS</span><button class="link-btn" data-page="shelf">Ver todos →</button></div>${[...state.data.library].reverse().map(b=>`<div class="recent-row"><img src="${b.cover}"><div><small>${b.month}</small><strong>${b.title}</strong><span>${b.author}</span></div><b>★★★★★</b></div>`).join("")}</article>
 </section>
 <section class="panel club-message"><div><span class="eyebrow">MENSAGEM DO CLUBE</span><h2>${state.data.settings.clubMessage}</h2><span>♥</span></div><img src="assets/illustrations/open-book.svg"></section>
 <section class="bottom-grid">
  <article class="panel mini-feature"><span class="eyebrow">ESCOLHA DO LIVRO</span><p>Tema atual: Romance</p><div class="feature-art">📕</div><strong>Sugestões abertas!</strong><small>Envie até 2 sugestões</small><button class="primary" data-page="choice">Ver sugestões</button></article>
  <article class="panel mini-feature"><span class="eyebrow">ESTANTE DO CLUBE</span><p>37 livros lidos</p><img src="assets/illustrations/shelf.svg"><button class="outline" data-page="shelf">Ver estante</button></article>
  <article class="panel mini-feature"><span class="eyebrow">HISTÓRICO</span><p>16 encontros realizados</p><div class="feature-art">📗🌹</div><button class="outline" data-page="history">Ver histórico</button></article>
 </section>`
}
function home2(){
 const b=state.data.currentBook,best=state.selectedDates.slice(0,4).map((d,i)=>({count:Math.max(2,5-i),period:{label:new Date(d+"T12:00:00").toLocaleDateString("pt-BR",{weekday:"long"}).replace("-feira",""),hint:new Date(d+"T12:00:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"long"})}}));
 return `<header class="greeting"><div><h1>Boa noite, Juliana!</h1><p>Que bom ter você aqui.</p></div><div class="header-icons"><button>♡</button><button>⚙</button></div></header><section class="hero panel"><img class="hero-cover" src="${b.cover}"><div class="hero-copy"><div class="hero-tags"><span>LIVRO DO MÊS</span><b>Agosto 2024</b></div><h2>${b.title}</h2><h3>${b.author}</h3><p>${b.description}</p><div class="hero-meta"><span>⌑ <b>DATA</b><strong>24 de Agosto</strong></span><span>◷ <b>HORÁRIO</b><strong>19h30</strong></span><span>⌖ <b>LOCAL</b><strong>Café Literário Breve</strong></span></div><button class="primary" data-page="schedule">Ver detalhes&nbsp; →</button></div><img class="hero-art" src="assets/illustrations/open-book.svg"></section><section class="dashboard-grid"><article class="panel upcoming"><div class="card-heading"><h2>Próximos Encontros</h2><span>▣</span></div>${state.data.upcomingMeetings.map((m,i)=>`<div class="upcoming-row ${i===0?"selected":""}"><strong>${m.date.split("/")[0]}</strong><div><small>${m.month}</small><span>${m.book}</span></div><b>•</b></div>`).join("")}<button class="outline" data-page="schedule">Ver calendário completo</button></article><article class="panel availability-summary"><div class="card-heading"><h2>Disponibilidade</h2><small>Agosto · 8 participantes</small></div><div class="availability-cards">${best.map((x,i)=>`<article class="${i===0?"best":""}"><strong>${x.period.label}</strong><small>${x.period.hint||"19h – 22h"}</small><div class="availability-bar"><i style="width:${Math.max(18,x.count*12.5)}%"></i></div><span>${x.count}<em>/8</em></span></article>`).join("")}</div></article></section><section class="dashboard-grid lower"><article class="panel participants-box"><div class="card-heading"><h2>Participantes</h2><span>♙</span></div>${state.data.participants.slice(0,5).map((p,i)=>`<div class="participant-row"><img src="${p.photo}"><div><strong>${p.name}</strong><small>${i===2||i===4?"Pendente":"Confirmada"}</small></div><b>•</b></div>`).join("")}<button class="outline" data-page="people">Ver todos</button></article><article class="panel recent-books"><div class="card-heading"><h2>Últimos Lidos</h2><span>▭</span></div>${[...state.data.library].reverse().map(b=>`<div class="recent-row"><img src="${b.cover}"><div><strong>${b.title}</strong><span>${b.author}</span><b>★★★★★ <small>${b.rating||"4.5"}</small></b></div><i>›</i></div>`).join("")}</article></section>`
}
function miniCalendar(){
 const [y,m]=state.data.availability.month.split("-").map(Number),first=new Date(y,m-1,1),last=new Date(y,m,0),cells=[];
 for(let i=0;i<first.getDay();i++)cells.push("<span></span>");
 for(let d=1;d<=last.getDate();d++){const iso=`${y}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`,sel=state.selectedDates.includes(iso);cells.push(`<button class="${sel?"selected":""}" data-toggle-date="${iso}">${d}</button>`)}
 return `<div class="calendar"><div class="cal-head"><button>‹</button><strong>${formatDate(first,{month:"long",year:"numeric"})}</strong><button>›</button></div><div class="week">${["D","S","T","Q","Q","S","S"].map(x=>`<span>${x}</span>`).join("")}</div><div class="days">${cells.join("")}</div></div>`
}
function schedule(){
 const periods=state.data.availability.periods;
 return `<header class="page-head deco-head"><div><span class="eyebrow">ESCOLHA DE HORÁRIOS</span><h1>Encontro de Agosto</h1><p>Marque todos os dias e períodos que você puder participar.</p></div><img src="assets/illustrations/cup-books.svg"></header>
 <section class="schedule-grid">
  <article class="panel calendar-box"><h2>Quais dias funcionam para você?</h2><p>Clique nos dias do calendário para selecionar.</p>${miniCalendar()}<div class="hint-box">✎ Selecione todos os dias em que você pode participar do encontro.</div></article>
  <article class="panel choices-box"><h2>Dias que você pode</h2><p>Agora escolha os períodos do dia em que você tem disponibilidade.</p><div class="selected-days">${state.selectedDates.map(d=>`<button data-remove-date="${d}"><small>${formatDate(new Date(d+"T12:00:00"),{weekday:"short"}).replace(".","")}</small><strong>${d.slice(-2)}</strong><span>${formatDate(new Date(d+"T12:00:00"),{month:"short"}).replace(".","")}</span><b>×</b></button>`).join("")}</div>
   <div class="availability-table"><div class="table-head"><span></span>${periods.map(p=>`<span><b>${p.label}</b><small>${p.hint}</small></span>`).join("")}</div>${state.selectedDates.map(d=>`<div class="table-row"><strong>${formatDate(new Date(d+"T12:00:00"),{weekday:"long"}).toUpperCase()}<small>${d.slice(8,10)}/${d.slice(5,7)}</small></strong>${periods.map(p=>{const k=`${d}|${p.id}`,checked=state.selectedChoices.has(k),count=countFor(d,p.id);return `<label><input type="checkbox" data-choice="${k}" ${checked?"checked":""}><i></i><span>${count} ${count===1?"pessoa":"pessoas"}</span></label>`}).join("")}</div>`).join("")}</div>
   <div class="save-note"><img src="assets/illustrations/open-book.svg"><div><strong>Você marcou ${state.selectedChoices.size} períodos de disponibilidade.</strong><span>Quanto mais opções você marcar, mais fácil será encontrar o melhor horário para todas!</span></div></div>
   <button class="primary full" data-action="save-my-availability">Salvar minha disponibilidade</button>
  </article>
 </section>
 <section class="panel how"><h2>Como funciona?</h2><div><span>1</span><p>Selecione todos os dias que você pode participar.</p><span>2</span><p>Escolha manhã, tarde ou noite.</p><span>3</span><p>As respostas serão combinadas e o melhor horário será definido.</p></div></section>`
}
function choice(){
 const s=state.data.suggestions,w=s.find(x=>x.id===state.data.selectedSuggestionId);
 return `<header class="page-head"><div><span class="eyebrow">PRÓXIMA LEITURA</span><h1>Escolha do livro</h1><p>Cadastre as sugestões do mês e acompanhe o sorteio.</p></div></header>
 <section class="panel choice-hero"><div><span class="eyebrow">TEMA DO MÊS</span><h2>Romance</h2><p>Cada participante pode sugerir até dois livros.</p></div><div class="choice-steps"><span>1 Sugestões</span><span>2 Encerramento</span><span>3 Sorteio</span></div></section>
 <div class="section-title block"><div><h2>Livros sugeridos</h2><p>${s.length} sugestões cadastradas</p></div><button class="primary" data-action="suggestion-form">Sugerir livro</button></div>
 <section class="suggestion-grid">${s.map((x,i)=>`<article class="panel suggestion-card"><span class="num">${String(i+1).padStart(2,"0")}</span><img src="${x.cover}"><div><small>SUGERIDO POR ${x.suggestedBy.toUpperCase()}</small><h2>${x.title}</h2><h3>${x.author}</h3><p>${x.description}</p><div class="chips"><span>${x.pages} páginas</span><span>Romance</span></div><div><a class="outline" href="${x.link}" target="_blank">Ver livro</a>${state.admin?`<button class="soft" data-remove-suggestion="${x.id}">Excluir</button>`:""}</div></div></article>`).join("")}</section>
 <section class="panel draw-box"><div><span class="eyebrow">SORTEIO JUSTO</span><h2>${w?"Livro escolhido":"Prontas para o sorteio?"}</h2><p>${w?`${w.title}, de ${w.author}. Sugestão de ${w.suggestedBy}.`:"Primeiro o sistema sorteia uma participante e depois uma das sugestões dela."}</p></div>${state.admin?`<button class="primary" data-action="draw-book">✦ Realizar sorteio</button>`:""}</section>`
}
function shelf(){return `<header class="page-head"><div><span class="eyebrow">NOSSA HISTÓRIA</span><h1>Estante do clube</h1><p>Todos os livros que já passaram pelos nossos encontros.</p></div></header><div class="section-title block"><div><h2>Livros lidos</h2><p>${state.data.library.length} livros cadastrados</p></div>${state.admin?`<button class="primary" data-action="library-form">Cadastrar livro</button>`:""}</div><section class="bookshelf">${state.data.library.map(b=>`<button data-book="${b.id}"><img src="${b.cover}"><span>${b.title}</span></button>`).join("")}</section>`}
function people(){return `<header class="page-head"><div><span class="eyebrow">NOSSO CLUBE</span><h1>Participantes</h1><p>Perfis e contatos das leitoras.</p></div></header><div class="section-title block"><div><h2>Quem faz parte</h2><p>${state.data.participants.length} participantes</p></div><button class="primary" data-action="profile-form">Cadastrar meu perfil</button></div><section class="people-grid">${state.data.participants.map(p=>`<article class="panel person-card"><img src="${p.photo}"><h2>${p.name}</h2><small>${p.favorite}</small><p>${p.bio}</p><button class="soft" data-person="${p.id}">Ver perfil</button></article>`).join("")}</section>`}
function history(){return `<header class="page-head"><div><span class="eyebrow">MEMÓRIAS</span><h1>Histórico</h1><p>Encontros e leituras que já vivemos juntas.</p></div></header>${state.data.library.map(b=>`<article class="panel history-row"><img src="${b.cover}"><div><span>${b.month}</span><h2>${b.title}</h2><p>${b.author}</p><b>★★★★★</b><small>${b.notes}</small></div></article>`).join("")}`}
function messages(){return `<header class="page-head"><div><span class="eyebrow">RECADOS</span><h1>Mensagens</h1><p>Comunicados do clube.</p></div></header><article class="panel club-message standalone"><div><h2>${state.data.settings.clubMessage}</h2><span>♥</span></div><img src="assets/illustrations/open-book.svg"></article>`}
function more(){return `<header class="page-head"><div><span class="eyebrow">MAIS</span><h1>Outras opções</h1></div></header><section class="bottom-grid"><article class="panel mini-feature"><span class="eyebrow">SOBRE O CLUBE</span><p>Biblioteca Noturna</p><div class="feature-art">☾📚</div></article><article class="panel mini-feature"><span class="eyebrow">CONFIGURAÇÕES</span><button class="outline" id="adminInside">Abrir painel administrativo</button></article></section>`}
function render(){renderNav();const views={home:home2,schedule,choice,shelf,people,history,messages,more};content.innerHTML=views[state.page]()}
function about(){return `<header class="page-head"><div><span class="eyebrow">NOSSA HISTÓRIA</span><h1>Sobre o clube</h1><p>Conheça a Biblioteca Noturna e os momentos que construímos juntas.</p></div></header><section class="about-hero panel"><div><span class="eyebrow">Biblioteca Noturna</span><h2>Um clube feito para compartilhar histórias, conversas e bons encontros.</h2><p>Nosso clube nasceu da vontade de transformar a leitura em uma experiência compartilhada. A cada mês escolhemos um novo livro, marcamos um encontro presencial e criamos memórias entre páginas, cafés e conversas.</p><div class="about-stats"><div><strong>2026</strong><small>Ano de início</small></div><div><strong>8</strong><small>Participantes</small></div><div><strong>${state.data.library.length}</strong><small>Livros lidos</small></div></div></div><img src="assets/illustrations/open-book.svg"></section><div class="section-title block"><div><h2>Momentos do clube</h2><p>Fotos dos encontros, leituras e memórias compartilhadas.</p></div></div><section class="about-memory panel"><img src="assets/illustrations/books-flowers.svg"><p>Em breve, este espaço vai guardar as melhores lembranças dos nossos encontros.</p></section>`}
function schedule2(){const dates=["2026-08-14","2026-08-15","2026-08-16","2026-08-17"];const suggestions=dates.map((d,i)=>({d,count:8-Math.min(3,i)}));return `<header class="page-head"><div><span class="eyebrow">ENCONTRO DE AGOSTO</span><h1>Quando você não pode?</h1><p>Marque apenas os dias e períodos em que você não poderá participar.</p></div></header><section class="schedule-new"><article class="panel unavailable-box"><div class="card-heading"><h2>Suas indisponibilidades</h2><small>Agosto · 8 participantes</small></div><p class="intro">Tudo que não for marcado será considerado uma possibilidade para você.</p>${dates.map(d=>`<div class="unavailable-day"><div><strong>${new Date(d+"T12:00:00").toLocaleDateString("pt-BR",{weekday:"long"})}</strong><small>${new Date(d+"T12:00:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"long"})}</small></div><label><input type="checkbox" data-choice="${d}|all" ${state.selectedChoices.has(d+"|all")?"checked":""}><span>Dia inteiro</span></label><label><input type="checkbox" data-choice="${d}|morning" ${state.selectedChoices.has(d+"|morning")?"checked":""}><span>Manhã</span></label><label><input type="checkbox" data-choice="${d}|afternoon" ${state.selectedChoices.has(d+"|afternoon")?"checked":""}><span>Tarde</span></label><label><input type="checkbox" data-choice="${d}|evening" ${state.selectedChoices.has(d+"|evening")?"checked":""}><span>Noite</span></label></div>`).join("")}<button class="primary full" data-action="save-my-availability">Salvar indisponibilidades</button></article><article class="panel suggestions-box"><div class="card-heading"><h2>Possíveis datas</h2><span>✦</span></div><p class="intro">O site cruza as respostas do grupo e sugere as melhores opções.</p>${suggestions.map((x,i)=>`<div class="suggested-date ${i===0?"recommended":""}"><strong>${new Date(x.d+"T12:00:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"long"})}</strong><div><span>${i%2?"Tarde":"Noite"}</span><small>${x.count} de 8 pessoas disponíveis</small></div><b>${i===0?"Melhor opção":""}</b></div>`).join("")}<button class="outline full" data-page="home">Voltar ao início</button></article></section>`}
function schedule3(){return schedule().replace("ESCOLHA DE HORÁRIOS","INDISPONIBILIDADES").replace("Encontro de Agosto","Quando você não pode?").replace("Marque todos os dias e períodos que você puder participar.","Marque os dias e períodos em que você não poderá participar.").replace("Quais dias funcionam para você?","Em quais dias você não pode participar?").replace("Clique nos dias do calendário para selecionar.","Selecione no calendário os dias em que você não poderá ir.").replace("Dias que você pode","Indisponibilidades").replace("Agora escolha os períodos do dia em que você tem disponibilidade.","Agora marque os períodos em que você não poderá participar.").replace("Salvar minha disponibilidade","Salvar indisponibilidades").replace("Você marcou","Você marcou").replace("períodos de disponibilidade","períodos de indisponibilidade").replace("Quanto mais opções você marcar, mais fácil será encontrar o melhor horário para todas!","O site vai considerar os outros dias e períodos como possibilidades para você.").replace("pessoas","indisponíveis").replace('<div class="save-note">','<div class="suggestion-notice"><strong>O site vai sugerir as melhores datas automaticamente</strong><span>Depois que todas responderem, vamos cruzar as indisponibilidades e mostrar as combinações com mais participantes disponíveis.</span></div><div class="save-note">')}
function home3(){return home2()+`<section class="panel participants-box home-participants"><div class="card-heading"><div><span class="eyebrow">PARTICIPANTES</span><p>5 de 8 responderam</p></div><button class="link-btn" data-page="people">Ver todos →</button></div><div class="home-avatars">${state.data.participants.map((p,i)=>`<div><img src="${p.photo}"><small>${i===0?"Você":p.name.split(" ")[0]}</small>${i<5?`<b>✓</b>`:""}</div>`).join("")}</div></section><section class="home-features"><article class="panel mini-feature"><span class="eyebrow">ESCOLHA DO LIVRO</span><p>Tema atual: Romance</p><div class="feature-art">▰</div><strong>Sugestões abertas!</strong><small>Envie até 2 sugestões</small><button class="primary" data-page="choice">Ver sugestões</button></article><article class="panel mini-feature"><span class="eyebrow">ESTANTE DO CLUBE</span><p>${state.data.library.length} livros lidos</p><div class="feature-art">▤</div><button class="outline" data-page="shelf">Ver estante</button></article><article class="panel mini-feature"><span class="eyebrow">HISTÓRICO</span><p>16 encontros realizados</p><div class="feature-art">▰ ✿</div><button class="outline" data-page="history">Ver histórico</button></article></section>`}
function home5(){const participants=`<section class="panel participants-box home-participants"><div class="card-heading"><div><span class="eyebrow">PARTICIPANTES</span><p>5 de 8 responderam</p></div><button class="link-btn" data-page="people">Ver todos →</button></div><div class="home-avatars">${state.data.participants.map((p,i)=>`<div><img src="${p.photo}"><small>${i===0?"Você":p.name.split(" ")[0]}</small>${i<5?`<b>✓</b>`:""}</div>`).join("")}</div></section>`;const books=`<section class="panel home-library"><div class="card-heading"><div><span class="eyebrow">ÚLTIMOS LIVROS</span><h2>Últimos Lidos</h2></div><button class="link-btn" data-page="shelf">Ver todos →</button></div><div class="home-library-list">${[...state.data.library].reverse().map(b=>`<div class="home-book"><img src="${b.cover}"><div><strong>${b.title}</strong><span>${b.author}</span><b>★★★★★ <small>${b.rating||"4.5"}</small></b></div><i>›</i></div>`).join("")}</div></section>`;return home2()+participants+books}
function home6(){const books=`<section class="panel home-library home-library-small"><div class="card-heading"><div><span class="eyebrow">ÚLTIMOS LIVROS</span><h2>Últimos Lidos</h2></div><button class="link-btn" data-page="shelf">Ver todos →</button></div><div class="home-library-list">${[...state.data.library].reverse().map(b=>`<div class="home-book"><img src="${b.cover}"><div><strong>${b.title}</strong><span>${b.author}</span><b>★★★★★ <small>${b.rating||"4.5"}</small></b></div><i>›</i></div>`).join("")}</div></section>`;const participants=`<section class="panel participants-box home-participants home-participants-wide"><div class="card-heading"><div><span class="eyebrow">PARTICIPANTES</span><p>5 de 8 responderam</p></div><button class="link-btn" data-page="people">Ver todos →</button></div><div class="home-avatars">${state.data.participants.map((p,i)=>`<div><img src="${p.photo}"><small>${i===0?"Você":p.name.split(" ")[0]}</small>${i<5?`<b>✓</b>`:""}</div>`).join("")}</div></section>`;return home2()+books+participants}
function homeAvailabilitySummary(){const unavailable=new Set(state.data.availability.responses.flatMap(r=>r.choices||[]).map(c=>c.split("|")[0]));const days=Array.from({length:31},(_,i)=>String(i+1).padStart(2,"0"));return `<div class="card-heading"><div><h2>Indisponibilidades</h2><p class="availability-help">Os dias com × estão indisponíveis para alguém do grupo.</p></div><small>Agosto · 8 participantes</small></div><div class="availability-summary-layout"><div class="mini-month"><strong>Agosto 2026</strong><div class="month-grid">${days.map(d=>`<span class="${unavailable.has("2026-08-"+d)?"marked":""}">${Number(d)}</span>`).join("")}</div></div><div class="marked-list">${[...unavailable].slice(0,4).map(d=>{const names=state.data.availability.responses.filter(r=>(r.choices||[]).some(c=>c.startsWith(d))).map(r=>r.name.split(" ")[0]);return `<div><strong>${d.slice(-2)}/08</strong><small>${names.length?names.join(", "):"Indisponibilidade marcada"}</small></div>`}).join("")||"<p>Nenhuma indisponibilidade marcada ainda.</p>"}</div></div>`}
const _render=render;render=function(){renderNav();const views={home:home6,schedule:schedule3,choice,shelf,people,history,about};content.innerHTML=views[state.page]();if(state.page==="home"){const av=document.querySelector(".availability-summary");if(av)av.innerHTML=homeAvailabilitySummary();const lib=document.querySelector(".home-library-small"),people=document.querySelector(".home-participants-wide");if(lib&&people){const wrap=document.createElement("div");wrap.className="home-bottom-grid";lib.parentNode.insertBefore(wrap,lib);wrap.append(lib,people)}const pt=document.querySelector(".home-participants-wide .eyebrow");if(pt)pt.textContent="Participantes"}}
function showAvailabilityIdentity(){openModal(`<h2>Salvar disponibilidade</h2><p class="modal-intro">Use sempre o mesmo nome e código para atualizar sua resposta depois.</p><div class="form-grid"><label>Nome<input id="avName" value="Juliana"></label><label>Código pessoal<input id="avCode" value="ju"></label></div><div class="modal-footer"><button class="primary" data-action="confirm-availability">Salvar</button></div>`)}
function showProfileForm(p={}){openModal(`<h2>${p.id?"Editar perfil":"Meu perfil"}</h2><div class="form-grid"><label>Nome<input id="pName" value="${escapeHtml(p.name||"")}"></label><label>Telefone<input id="pPhone" value="${escapeHtml(p.phone||"")}"></label><label>Aniversário<input id="pBirthday" type="date" value="${escapeHtml(p.birthday||"")}"></label><label>Instagram<input id="pInstagram" value="${escapeHtml(p.instagram||"")}"></label><label>Gênero favorito<input id="pFavorite" value="${escapeHtml(p.favorite||"")}"></label><label class="full">Sobre você<textarea id="pBio">${escapeHtml(p.bio||"")}</textarea></label><div class="full">${imageUploadField("pPhoto",p.photo||"")}</div></div><div class="modal-footer"><button class="primary" data-save-person="${p.id||""}">Salvar perfil</button></div>`,true);bindPreview("pPhoto")}
async function savePerson(id){const p={id:id||crypto.randomUUID(),name:pName.value.trim(),phone:pPhone.value.trim(),birthday:pBirthday.value,instagram:pInstagram.value.trim(),favorite:pFavorite.value.trim(),bio:pBio.value.trim(),photo:await resolvedImage("pPhoto")};if(!p.name)return showToast("Informe o nome.");const i=state.data.participants.findIndex(x=>x.id===p.id);i>=0?state.data.participants[i]=p:state.data.participants.push(p);closeModal();save("Perfil salvo.")}
function showSuggestionForm(){openModal(`<h2>Sugerir livro</h2><div class="form-grid"><label class="full">Link da Amazon, Skoob ou outro site<input id="sLink"></label><label>Título<input id="sTitle"></label><label>Autor<input id="sAuthor"></label><label>Páginas<input id="sPages"></label><label>Seu nome<input id="sBy"></label><label class="full">Sinopse<textarea id="sDescription"></textarea></label><div class="full">${imageUploadField("sCover","")}</div></div><div class="modal-footer"><button class="soft" data-action="lookup-book">Buscar dados</button><button class="primary" data-action="save-suggestion">Cadastrar</button></div>`,true);bindPreview("sCover")}
async function lookupBook(){const q=sTitle.value||sLink.value;if(!q)return showToast("Digite o título ou cole um link.");showToast("Buscando...");try{const r=await fetch(`https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(q)}&maxResults=1`),j=await r.json(),b=j.items?.[0]?.volumeInfo;if(!b)return showToast("Livro não encontrado.");sTitle.value=b.title||"";sAuthor.value=(b.authors||[]).join(", ");sPages.value=b.pageCount||"";sDescription.value=b.description||"";const cover=(b.imageLinks?.thumbnail||"").replace("http:","https:");sCoverUrl.value=cover;sCoverPreview.innerHTML=cover?`<img src="${cover}">`:"";showToast("Informações encontradas.")}catch{showToast("Não foi possível buscar. Preencha manualmente.")}}
async function saveSuggestion(){const s={id:crypto.randomUUID(),title:sTitle.value.trim(),author:sAuthor.value.trim(),pages:sPages.value.trim(),suggestedBy:sBy.value.trim(),description:sDescription.value.trim(),link:sLink.value.trim(),cover:await resolvedImage("sCover")};if(!s.title||!s.suggestedBy)return showToast("Informe título e participante.");state.data.suggestions.push(s);closeModal();save("Sugestão cadastrada.")}
function showLibraryForm(){openModal(`<h2>Cadastrar livro</h2><div class="form-grid"><label>Título<input id="lTitle"></label><label>Autor<input id="lAuthor"></label><label>Mês<input id="lMonth"></label><label>Nota<input id="lRating" type="number" min="0" max="5" step=".1"></label><label class="full">Comentário<textarea id="lNotes"></textarea></label><div class="full">${imageUploadField("lCover","")}</div></div><div class="modal-footer"><button class="primary" data-action="save-library">Adicionar à estante</button></div>`,true);bindPreview("lCover")}
async function saveLibrary(){const b={id:crypto.randomUUID(),title:lTitle.value.trim(),author:lAuthor.value.trim(),month:lMonth.value.trim(),rating:lRating.value,notes:lNotes.value.trim(),cover:await resolvedImage("lCover")};if(!b.title)return showToast("Informe o título.");state.data.library.push(b);closeModal();save("Livro adicionado.")}
function adminLogin(){if(state.admin)return adminPanel();openModal(`<h2>Área administrativa</h2><label>Senha<input id="adminPass" type="password"></label><div class="modal-footer"><button class="primary" data-action="check-admin">Entrar</button></div>`)}
function adminPanel(){openModal(`<h2>Painel administrativo</h2><div class="admin-grid"><button data-action="identity-settings"><b>✦</b><span>Identidade visual</span><small>Logo, cores, favicon e citação</small></button><button data-action="text-settings"><b>✎</b><span>Textos e títulos</span><small>Menu, mensagens e nome do clube</small></button><button data-action="book-settings"><b>▥</b><span>Livro do mês</span><small>Capa, sinopse e encontro</small></button><button data-action="library-form"><b>⌂</b><span>Estante</span><small>Adicionar livro lido</small></button><button data-action="security-settings"><b>⚙</b><span>Acesso</span><small>Senha e participantes</small></button></div><div class="modal-footer"><button class="outline" data-action="logout-admin">Sair do modo administrativo</button></div>`,true)}
function identitySettings(){const i=state.data.settings.identity;openModal(`<h2>Identidade visual</h2><div class="form-grid"><label>Cor principal<input id="idPrimary" type="color" value="${i.primaryColor}"></label><label>Cor secundária<input id="idSecondary" type="color" value="${i.secondaryColor}"></label><label>Cor de fundo<input id="idCream" type="color" value="${i.creamColor}"></label><label class="full">Citação<textarea id="idQuote">${i.quote}</textarea></label><label class="full">Autor<input id="idQuoteAuthor" value="${i.quoteAuthor}"></label><div class="full">${imageUploadField("idLogo",i.logo)}</div><div class="full">${imageUploadField("idFavicon",i.favicon)}</div></div><div class="modal-footer"><button class="primary" data-action="save-identity">Salvar</button></div>`,true);bindPreview("idLogo");bindPreview("idFavicon")}
async function saveIdentity(){const i=state.data.settings.identity;i.primaryColor=idPrimary.value;i.secondaryColor=idSecondary.value;i.creamColor=idCream.value;i.quote=idQuote.value;i.quoteAuthor=idQuoteAuthor.value;i.logo=await resolvedImage("idLogo");i.favicon=await resolvedImage("idFavicon");closeModal();save("Identidade atualizada.")}
function textSettings(){const i=state.data.settings.identity;openModal(`<h2>Textos e títulos</h2><div class="form-grid"><label>Texto pequeno<input id="clubEyebrow" value="${i.clubEyebrow}"></label><label>Nome do clube<input id="clubName" value="${i.clubName}"></label><label class="full">Mensagem do clube<textarea id="clubMessage">${state.data.settings.clubMessage}</textarea></label>${Object.entries(labels()).map(([k,v])=>`<label>${k}<input data-label="${k}" value="${v}"></label>`).join("")}</div><div class="modal-footer"><button class="primary" data-action="save-texts">Salvar</button></div>`,true)}
function saveTexts(){const i=state.data.settings.identity;i.clubEyebrow=clubEyebrow.value;i.clubName=clubName.value;state.data.settings.clubMessage=clubMessage.value;document.querySelectorAll("[data-label]").forEach(x=>state.data.settings.labels[x.dataset.label]=x.value);closeModal();save("Textos atualizados.")}
function bookSettings(){const b=state.data.currentBook;openModal(`<h2>Livro do mês</h2><div class="form-grid"><label>Título<input id="cTitle" value="${b.title}"></label><label>Autor<input id="cAuthor" value="${b.author}"></label><label>Páginas<input id="cPages" value="${b.pages}"></label><label>Gênero<input id="cGenre" value="${b.genre}"></label><label class="full">Sinopse<textarea id="cDesc">${b.description}</textarea></label><label class="full">Link de compra<input id="cLink" value="${b.purchaseLink}"></label><label>Data<input id="cDate" value="${b.meetingDate}"></label><label>Horário<input id="cTime" value="${b.meetingTime}"></label><label class="full">Local<input id="cPlace" value="${b.meetingPlace}"></label><div class="full">${imageUploadField("cCover",b.cover)}</div></div><div class="modal-footer"><button class="primary" data-action="save-current-book">Salvar</button></div>`,true);bindPreview("cCover")}
async function saveCurrentBook(){state.data.currentBook={title:cTitle.value,author:cAuthor.value,pages:cPages.value,genre:cGenre.value,description:cDesc.value,purchaseLink:cLink.value,meetingDate:cDate.value,meetingTime:cTime.value,meetingPlace:cPlace.value,cover:await resolvedImage("cCover")};closeModal();save("Livro atualizado.")}
function securitySettings(){openModal(`<h2>Acesso</h2><div class="form-grid"><label>Senha<input id="newPass" value="${state.data.settings.adminPassword}"></label><label>Total de participantes<input id="expected" type="number" value="${state.data.settings.expectedParticipants}"></label></div><div class="modal-footer"><button class="primary" data-action="save-security">Salvar</button></div>`)}
document.addEventListener("click",async e=>{
 const p=e.target.closest("[data-page]");if(p){state.page=p.dataset.page;render();return}
 if(e.target.closest("[data-close-modal]")||e.target.id==="modalBackdrop"){closeModal();return}
 const a=e.target.closest("[data-action]")?.dataset.action;
 const acts={"save-my-availability":showAvailabilityIdentity,"confirm-availability":()=>{const n=avName.value.trim(),c=avCode.value.trim();if(!n||!c)return showToast("Informe nome e código.");const i=state.data.availability.responses.findIndex(x=>x.name.toLowerCase()===n.toLowerCase()&&x.code===c);const r={name:n,code:c,choices:[...state.selectedChoices]};i>=0?state.data.availability.responses[i]=r:state.data.availability.responses.push(r);closeModal();save("Disponibilidade salva.")},"profile-form":()=>showProfileForm(),"suggestion-form":showSuggestionForm,"lookup-book":lookupBook,"save-suggestion":saveSuggestion,"draw-book":()=>{const g={};state.data.suggestions.forEach(x=>(g[x.suggestedBy]??=[]).push(x));const names=Object.keys(g),n=names[Math.floor(Math.random()*names.length)],list=g[n],w=list[Math.floor(Math.random()*list.length)];state.data.selectedSuggestionId=w.id;save("Livro sorteado: "+w.title)},"library-form":showLibraryForm,"save-library":saveLibrary,"check-admin":()=>{if(adminPass.value!==state.data.settings.adminPassword)return showToast("Senha incorreta.");state.admin=true;closeModal();render();showToast("Acesso liberado.")},"identity-settings":identitySettings,"save-identity":saveIdentity,"text-settings":textSettings,"save-texts":saveTexts,"book-settings":bookSettings,"save-current-book":saveCurrentBook,"security-settings":securitySettings,"save-security":()=>{state.data.settings.adminPassword=newPass.value;state.data.settings.expectedParticipants=Number(expected.value)||8;closeModal();save("Configurações salvas.")},"logout-admin":()=>{state.admin=false;closeModal();render()}};
 if(a&&acts[a]){e.preventDefault();await acts[a]();return}
 const t=e.target.closest("[data-toggle-date]");if(t){const d=t.dataset.toggleDate;state.selectedDates.includes(d)?state.selectedDates=state.selectedDates.filter(x=>x!==d):state.selectedDates.push(d);render();return}
 const r=e.target.closest("[data-remove-date]");if(r){state.selectedDates=state.selectedDates.filter(x=>x!==r.dataset.removeDate);[...state.selectedChoices].forEach(k=>{if(k.startsWith(r.dataset.removeDate))state.selectedChoices.delete(k)});render();return}
 const c=e.target.closest("[data-choice]");if(c){const k=c.dataset.choice;c.checked?state.selectedChoices.add(k):state.selectedChoices.delete(k);render();return}
 const sp=e.target.closest("[data-save-person]");if(sp){await savePerson(sp.dataset.savePerson);return}
 const per=e.target.closest("[data-person]");if(per){const p=state.data.participants.find(x=>x.id===per.dataset.person);openModal(`<h2>${p.name}</h2><div class="profile-detail"><img src="${p.photo}"><p>${p.bio}</p><div class="panel"><p>📞 ${p.phone}</p><p>🎂 ${p.birthday}</p><p>📚 ${p.favorite}</p><p>${p.instagram}</p></div></div>`);return}
 const rm=e.target.closest("[data-remove-suggestion]");if(rm){state.data.suggestions=state.data.suggestions.filter(x=>x.id!==rm.dataset.removeSuggestion);save("Sugestão removida.");return}
});
adminButton.onclick=adminLogin;profileShortcut.onclick=()=>showProfileForm(state.data.participants[0]);menuBtn.onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
document.addEventListener("click",e=>{if(e.target.id==="adminInside")adminLogin()});
function navItems(){return [["home","⌂","Início"],["schedule","▣","Encontro"],["choice","◈","Escolha do Livro"],["shelf","▥","Estante"],["people","♧","Participantes"],["history","◷","Histórico"],["about","♡","Sobre o Clube"]]}
function refFaces(amount=3){return state.data.participants.slice(0,amount).map(p=>`<img src="${p.photo}" alt="${p.name}">`).join("")}
function referenceHome(){const b=state.data.currentBook,meetings=state.data.upcomingMeetings;const books=[...state.data.library].reverse();const dates=["SEG|12/08", "TER|13/08", "QUA|14/08", "QUI|15/08", "SEX|16/08", "SÁB|17/08", "DOM|18/08"];return `<main class="reference-home"><header class="greeting"><div><h1>Boa noite, Juliana! <em>✦</em></h1><p>Que bom ter você aqui.</p></div><div class="header-icons"><button aria-label="Favoritos">♡</button><button aria-label="Notificações">♧</button></div></header><section class="reference-top"><article class="panel reference-hero"><img class="reference-cover" src="${b.cover}" alt="Capa de ${b.title}"><div class="reference-book-copy"><div class="reference-label"><b>★</b>LIVRO DO MÊS</div><h2>${b.title}</h2><h3>${b.author}</h3><p>${b.description}</p><div class="reference-meta"><span><i>▣</i>${b.meetingDate}</span><span><i>◷</i>${b.meetingTime}</span><span><i>⌖</i>${b.meetingPlace}</span></div><button class="reference-button" data-page="schedule">Ver detalhes do encontro <b>›</b></button></div><div class="reference-still" aria-hidden="true"></div></article><aside class="panel reference-upcoming"><h2>Próximos encontros</h2>${meetings.map((m,i)=>`<div class="reference-meeting ${m.active?"active":""}"><span class="meeting-icon">${i===0?"☾":i===1?"✦":"✧"}</span><div><b>${m.month}</b><span>${m.date}</span><small>${m.book}</small></div><i>›</i></div>`).join("")}<button class="reference-outline" data-page="schedule">▣ &nbsp; Ver calendário completo</button></aside></section><section class="panel reference-availability"><header><h2>Disponibilidade · Agosto</h2><button data-page="schedule">Ver todos os detalhes &nbsp; ›</button></header><div class="reference-days">${dates.map((d,i)=>{const [week,date]=d.split("|");const n=[5,6,4,8,3,2,4][i];return `<div class="reference-day ${i===3?"active":""}"><strong>${week}</strong><small>${date}</small><div class="reference-faces">${refFaces(Math.min(3,n))}<b>${n}</b></div><div class="reference-meter">${Array.from({length:5},(_,x)=>`<i class="${x<Math.ceil(n/2)?"on":""}"></i>`).join("")}</div></div>`}).join("")}</div></section><section class="reference-bottom"><article class="panel reference-recent"><div class="reference-card-head"><h2>Últimos livros lidos</h2><button data-page="shelf">Ver todos</button></div><div class="reference-book-list">${books.map(book=>`<div class="reference-small-book"><img src="${book.cover}" alt="${book.title}"><div><strong>${book.title}</strong><span>${book.author}</span><b>★ ${book.rating||"4.7"}</b></div></div>`).join("")}</div></article><article class="panel reference-people"><div class="reference-card-head"><h2>Participantes recentes</h2><button data-page="people">Ver todos</button></div><div class="reference-people-list">${state.data.participants.slice(0,4).map(p=>`<div class="reference-person"><img src="${p.photo}" alt="${p.name}"><b>★</b><span>${p.name}</span></div>`).join("")}</div></article></section></main>`}
render=function(){renderNav();const views={home:referenceHome,schedule:schedule3,choice,shelf,people,history,about};content.innerHTML=(views[state.page]||referenceHome)()}
window.BibliotecaApp={getState:()=>state,render:()=>render()};
applyIdentity();render();
