const participants=["Ana Cristina","Bianca","Larissa","Luana","Maria Eduarda","Pricila","Rhullya","Tainara"];
const demoResponses={Bianca:["2026-08-29","2026-08-30"],Pricila:["2026-08-29","2026-08-30"],Luana:["2026-08-29","2026-08-30"],Tainara:["2026-08-29"],Rhullya:["2026-08-29","2026-08-30"],"Ana Cristina":["2026-08-29"]};
let month=new Date(2026,7,1),selectedName="",draft=[];
const qs=s=>document.querySelector(s),calendar=qs("#calendar"),formatter=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}),dayFormat=new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"numeric",month:"long"});
function key(date){return date.toISOString().slice(0,10)}
function initials(name){return name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}
function prettyDate(k){return dayFormat.format(new Date(`${k}T12:00:00`)).replace(/^(.)/,(_,c)=>c.toUpperCase())}
function allResponses(){return {...demoResponses,...(selectedName&&draft.length?{[selectedName]:draft}:{})}}
function renderCalendar(){qs("#monthTitle").textContent=formatter.format(month);calendar.innerHTML="";const first=month.getDay(),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),today=key(new Date());for(let i=0;i<first;i++)calendar.insertAdjacentHTML("beforeend",'<span class="empty"></span>');for(let d=1;d<=days;d++){const date=new Date(month.getFullYear(),month.getMonth(),d,12),k=key(date),past=k<today;calendar.insertAdjacentHTML("beforeend",`<button type="button" data-day="${k}" class="${draft.includes(k)?"selected":""} ${k===today?"today":""}" ${past?"disabled":""}>${d}</button>`)} }
function renderSummary(){const el=qs("#summary");el.hidden=!draft.length;el.innerHTML=`<h3>Dias selecionados</h3><div class="selected-chips">${draft.slice().sort().map(date=>`<span class="selected-chip">${prettyDate(date)}</span>`).join("")}</div>`;qs("#saveButton").disabled=!selectedName||!draft.length}
function tally(){const results={};for(const [person,dates] of Object.entries(allResponses()))for(const date of dates){results[date]??={date,people:new Set()};results[date].people.add(person)}return Object.values(results).sort((a,b)=>a.date.localeCompare(b.date))}
function avatars(names,responded=names){return names.map(name=>`<button type="button" class="avatar ${responded.includes(name)?"done":""}" data-person-name="${name}" aria-label="Ver nome de ${name}">${initials(name)}</button>`).join("")}
function renderResults(){const data=tally(),best=Math.max(0,...data.map(x=>x.people.size)),bests=data.filter(x=>x.people.size===best);qs("#bestOption").innerHTML=`<span class="eyebrow">MELHOR OPÇÃO ATÉ AGORA</span>${bests.length?bests.map(x=>`<div class="best-choice"><strong>${prettyDate(x.date)}</strong><span>${x.people.size} participantes podem</span></div>`).join(""):`<div class="best-choice"><span>Aguardando respostas.</span></div>`}`;const responded=Object.keys(allResponses()),pending=participants.filter(name=>!responded.includes(name));qs("#responses").innerHTML=`<span class="eyebrow">QUEM JÁ RESPONDEU</span><h2>${responded.length} de ${participants.length} responderam</h2><div class="avatar-list">${avatars(participants,responded)}</div><p class="pending">Ainda faltam: ${pending.join(", ")||"ninguém"}.</p>`;qs("#groupResults").innerHTML=`<span class="eyebrow">DISPONIBILIDADE DO GRUPO</span><h2>Possíveis datas</h2>${data.map(x=>`<article class="result-row" data-result-date="${x.date}"><div><strong>${prettyDate(x.date)}</strong><b>${x.people.size} podem</b></div><div class="avatar-list" style="justify-content:flex-start;gap:5px;margin:10px 0 0">${avatars([...x.people])}</div></article>`).join("")||"<p class='field-note'>As respostas aparecerão aqui.</p>"}`}
function refresh(){renderCalendar();renderSummary();renderResults()}
function syncName(){const name=qs("#participantName").value;selectedName=name;draft=demoResponses[name]?[...demoResponses[name]]:[];const n=qs("#replaceNotice");n.hidden=!selectedName||!demoResponses[selectedName];n.textContent=demoResponses[selectedName]?"Você já respondeu. Se quiser, pode ajustar os dias e salvar novamente.":"";refresh()}
qs("#participantName").addEventListener("change",syncName);
qs("#previousMonth").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderCalendar()};qs("#nextMonth").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderCalendar()};
calendar.addEventListener("click",e=>{const b=e.target.closest("[data-day]");if(!b)return;const k=b.dataset.day;draft.includes(k)?draft=draft.filter(x=>x!==k):draft.push(k);refresh()});
qs("#saveButton").onclick=()=>{demoResponses[selectedName]=[...draft];qs("#saveMessage").textContent=matchMedia("(max-width: 519px)").matches?"Resposta registrada. Você pode alterar quando quiser.":"Resposta registrada. Você pode voltar e alterar quando quiser.";refresh()};
qs("#groupResults").addEventListener("click",e=>{if(e.target.closest("[data-person-name]"))return;const row=e.target.closest("[data-result-date]");if(!row)return;const info=tally().find(x=>x.date===row.dataset.resultDate);qs("#detailsContent").innerHTML=`<h2>${prettyDate(info.date)}</h2><div class="detail-period"><strong>${info.people.size} participantes podem</strong><span>${[...info.people].join(", ")}</span></div>`;qs("#detailsDialog").showModal()});qs("#closeDialog").onclick=()=>qs("#detailsDialog").close();
qs("#detailsDialog").addEventListener("click",e=>{if(e.target===e.currentTarget)e.currentTarget.close()});
document.addEventListener("click",e=>{const avatar=e.target.closest("[data-person-name]"),touchDevice=matchMedia("(hover: none), (pointer: coarse)").matches;document.querySelectorAll(".avatar.show-tooltip").forEach(item=>{if(item!==avatar)item.classList.remove("show-tooltip")});if(avatar&&touchDevice){e.preventDefault();avatar.classList.toggle("show-tooltip")}});
refresh();
