function escapeHtml(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function openModal(html,wide=false){const m=document.getElementById("modal");m.className=wide?"modal modal-wide":"modal";m.innerHTML=`<button class="modal-close" data-close-modal>×</button>${html}`;document.getElementById("modalBackdrop").classList.remove("hidden")}
function closeModal(){document.getElementById("modalBackdrop").classList.add("hidden")}
function showToast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.remove("hidden");clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.add("hidden"),2800)}
function formatDate(date,opt={weekday:"long",day:"2-digit",month:"long"}){return new Intl.DateTimeFormat("pt-BR",opt).format(date)}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{if(!file)return resolve("");const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function imageUploadField(prefix,current=""){return `<div class="upload-box"><label>Imagem por link</label><input id="${prefix}Url" value="${escapeHtml(current)}" placeholder="https://..."><div class="or">ou</div><label class="upload-button">📷 Tirar foto ou escolher da galeria<input id="${prefix}File" type="file" accept="image/*" capture="environment" hidden></label><div id="${prefix}Preview" class="upload-preview">${current?`<img src="${escapeHtml(current)}">`:"<span>Nenhuma imagem selecionada</span>"}</div></div>`}
async function resolvedImage(prefix){const file=document.getElementById(prefix+"File")?.files?.[0];if(file)return await fileToDataUrl(file);return document.getElementById(prefix+"Url")?.value.trim()||""}
function bindPreview(prefix){const i=document.getElementById(prefix+"File");if(!i)return;i.addEventListener("change",async()=>{const src=await resolvedImage(prefix);document.getElementById(prefix+"Preview").innerHTML=src?`<img src="${src}">`:"<span>Nenhuma imagem selecionada</span>"})}
